title: 鱼说
description: 吾，即使鱼群！
theme: just-the-docs

url: https://theafish.github.io/theNotfishSaid/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
  
mathjax:
 source: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_CHTML
 config: 'MathJax.Hub.Config({ TeX: { equationNumbers: { autoNumber: "AMS" } } })'
