title: 魚说
description: 吾，即使鱼群！
theme: just-the-docs
color_scheme: seasky

url: https://theafish.github.io/theNotfishSaid/

aux_links:
  Template Repository: https://github.com/theAfish/theNotfishSaid
compress_html:
  blanklines: true
mathjax:
 source: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_CHTML
 config: 'MathJax.Hub.Config({ TeX: { equationNumbers: { autoNumber: "AMS" } } })'
